apiVersion: v1
kind: Service
metadata:
  name: agent-runtime
  namespace: agentcore-runtime
  labels:
    app.kubernetes.io/name: agentcore
    app.kubernetes.io/component: agent-runtime
spec:
  type: ClusterIP
  ports:
    - port: 8002
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: agentcore
    app.kubernetes.io/component: agent-runtime
